Arm joint control + simulation
robotique-udes/rover pull request #32
Opened 2024-06-26 23:01 UTC by emilesavoie

Simulation not included in rover_helper
To launch, use the following:
ros2 launch rover_sim rover_sim.launch.py

TESTS:
The configuration is kept while rover.launch.py is active
The arm can only be controlled while srv is called and deadman active

2024-06-30 21:00 UTC, Pmichaud29 requested changes
On revera un peu l'architecture ensemble, mais c'est spot on au niveau du controle et de la logique.

Revois aussi le noeud d'arbitration pour arm (dans cette pr) et drive_train (crée un issue et fait ça dans un autre pr après le control)

2024-06-30 21:00 UTC, Pmichaud29 commented on rover_arm/launch/arm.launch.py
> +                                                )
Encore bon?

2024-06-30 21:00 UTC, Pmichaud29 commented on rover_arm/package.xml
> +
Il manquerait ceux que t'as rajouter dans ton cmakefile:
  sensor_msgs
  tf2_ros

2024-06-30 21:00 UTC, Pmichaud29 commented on rover_arm/src/arbitration.cpp
> +    // opens instead
?

2024-06-30 21:00 UTC, Pmichaud29 commented on rover_msgs/msg/ArmCmd.msg
> +bool[7] close_loop
enleve le close_loop, le bras aura pas vrm le choix de tjrs être en close loop. Le enable aussi, on a pas de on/off, pis target_position and current_position peuvent devenir juste position (le nom de topic va être utilisé pour savoir si c'est target/goal ou current)

2024-06-30 21:00 UTC, Pmichaud29 commented on rover_sim/package.xml
> +
même chose qu'en haut, essaye d'être consistant avec le cmakefile

2024-06-30 21:00 UTC, Pmichaud29 commented on rover_sim/package.xml
> +    rover_security pkg contains heartbeat node
todo

2024-06-30 21:00 UTC, Pmichaud29 commented on rover_arm/package.xml
> +    rover_drive_train pkg contains teleop node
todo

2024-06-30 21:00 UTC, Pmichaud29 commented on rover_arm/CMakeLists.txt
> +                          sensor_msgs
valide que tu l'utilise vrm et si non enlève le

2024-06-30 21:00 UTC, Pmichaud29 commented on rover_arm/src/arbitration.cpp
> +        _pubAbtr->publish(_zeroCmd);
_zeroCmd pourrait être initialisé à 0 dans le constructeur pour pas avoir besoin de le creer à chaque loop vue qu'il change pas

2024-06-30 21:00 UTC, Pmichaud29 commented on rover_arm/src/arbitration.cpp
> +
ctrl+shift+i

2024-06-30 21:00 UTC, Pmichaud29 commented on rover_arm/src/arbitration.cpp
> +        _pubAbtr->publish(_zeroCmd);
comme en haut, pourrait être une methode: void sendZero() pour éviter le copier collé

2024-06-30 21:00 UTC, Pmichaud29 commented on rover_arm/src/arbitration.cpp
> +    rclcpp::Service<rover_msgs::srv::DriveTrainArbitration>::SharedPtr _srvControlDemux;
On dirait que tu as oublié de le link avec ton cbAbtr (il semble pas être init). Aussi les noms sont pour le drivetrain. Valide si t'as pas oublié dans le drive_train aussi.

2024-06-30 21:00 UTC, Pmichaud29 commented on rover_arm/src/arbitration.cpp
À retravailler en fonction des nouveaux messages de bras et autre. On dirait que tu as copier coller le code de drive_train et que tu as oublié que c'était là

2024-06-30 21:00 UTC, Pmichaud29 commented on rover_arm/src/teleop.cpp
> +                RCLCPP_INFO(this->get_logger(), "Inverse kinematics mode NOT YET AVAILABLE");
RCLCPP_ERR

2024-06-30 21:00 UTC, Pmichaud29 commented on rover_arm/src/teleop.cpp
> +    Teleop *teleop;
Drôle de pointeur ahah à quoi il sert?

2024-06-30 21:00 UTC, Pmichaud29 commented on rover_arm/src/teleop.cpp
> +                    _currentJ0 += _j0Control * _speedControl * -1;
-1.0f

2024-06-30 21:00 UTC, Pmichaud29 commented on rover_arm/src/teleop.cpp
> +    float _endEffectorLength = 210.1945f;
À mettre dans un yaml et parser à l'init

2024-06-30 21:00 UTC, Pmichaud29 commented on rover_arm/src/teleop.cpp
> +        joint_state.position = {_currentLinear, _currentJ0, _currentJ1, _currentJ2, _currentGripperUD, _currentGripperLR};
On va compartimentaliser ça dans un noeud dans le package sim. En gros le teleop devrait juste publié des positions target en fonction du current position. Mais c'est au sim/affichage d'aller chercher l'information qu'il a besoin et de la publié sur le format nécéssaire (joint_state + transoformBroadcast)

2024-06-30 21:00 UTC, Pmichaud29 commented on rover_arm/src/teleop.cpp
> +#include "tf2_ros/transform_broadcaster.h"
rm (voir commentaire plus bas)

2024-06-30 21:00 UTC, Pmichaud29 commented on rover_arm/src/teleop.cpp
> +    float _currentGripperOC = 0.0f;
Trouve des noms un peu plus parlant genre currentPosLinear / targetPosLinear ou wtv

2024-06-30 21:00 UTC, Pmichaud29 commented on rover_arm/src/teleop.cpp
> +    float _currentGripperOC = 0.0f;
C'est au simulateur (un autre noeud) de publié ça sur le topic qui serait normalement celui des encodeurs

2024-07-02 02:51 UTC, emilesavoie commented on rover_msgs/msg/ArmCmd.msg
> +bool[7] close_loop
Solved

2024-07-02 02:59 UTC, emilesavoie commented on rover_sim/package.xml
> +
Done

2024-07-02 02:59 UTC, emilesavoie commented on rover_sim/package.xml
> +    rover_security pkg contains heartbeat node
Done

2024-07-02 03:00 UTC, emilesavoie commented on rover_arm/package.xml
> +    rover_drive_train pkg contains teleop node
Done

2024-07-02 03:01 UTC, emilesavoie commented on rover_arm/CMakeLists.txt
> +                          sensor_msgs
Enlever sensor_msgs

2024-07-02 03:02 UTC, emilesavoie commented on rover_arm/src/teleop.cpp
> +                RCLCPP_INFO(this->get_logger(), "Inverse kinematics mode NOT YET AVAILABLE");
Done

2024-07-02 03:03 UTC, emilesavoie commented on rover_arm/src/teleop.cpp
> +    Teleop *teleop;
Aucune idee haha. removed

2024-07-02 03:03 UTC, emilesavoie commented on rover_arm/src/teleop.cpp
> +                    _currentJ0 += _j0Control * _speedControl * -1;
done

2024-07-02 03:04 UTC, emilesavoie commented on rover_arm/src/teleop.cpp
> +        joint_state.position = {_currentLinear, _currentJ0, _currentJ1, _currentJ2, _currentGripperUD, _currentGripperLR};
Done!

2024-07-02 03:04 UTC, emilesavoie commented on rover_arm/src/teleop.cpp
> +#include "tf2_ros/transform_broadcaster.h"
done

2024-07-02 03:06 UTC, emilesavoie commented on rover_arm/src/teleop.cpp
> +    float _currentGripperOC = 0.0f;
Done

2024-07-02 03:06 UTC, emilesavoie commented on rover_arm/src/teleop.cpp
> +    float _currentGripperOC = 0.0f;
Changed to relevant file

2024-07-07 19:17 UTC, Pmichaud29 commented on rover_arm/src/teleop.cpp
> +        _gripperMode = joyMsg->joy_data[rover_msgs::msg::Joy::R1];
Garde c'est variables là local au callback

2024-07-07 19:40 UTC, Pmichaud29 requested changes
Ça s'en vient, plusieurs commentaires sur l'organisation mais la logique est là et au niveau de l'architecture ça fait ben du sens.

Pense aussi à updater le schema d'arch sur teams

2024-07-07 19:40 UTC, Pmichaud29 commented on rover_arm/src/teleop.cpp
> +    float _gripperC;
Soit plus explicite dans tes noms de variables
Ex: _posCmdJL, _gripperUpDown ou _gripperTilt / _gripperRot

2024-07-07 19:40 UTC, Pmichaud29 commented on rover_arm/src/teleop.cpp
> +
Même chose qu'en haut;
dequoi comme:
_posCmdJL
_posCurrentJL
serait plus évident

2024-07-07 19:40 UTC, Pmichaud29 commented on rover_arm/src/teleop.cpp
> +        rover_msgs::msg::ArmCmd armMsg;
Pourrait être global pour éviter l'allocation à chaque loop comme les autres variables

2024-07-07 19:40 UTC, Pmichaud29 commented on rover_arm/src/teleop.cpp
> +    float _speedControl = 0.0017453f; // 10 deg/s - (0.1745 rad/s)
Define ou un constexpr

2024-07-07 19:40 UTC, Pmichaud29 commented on rover_arm/src/teleop.cpp
> +    float _inverseKinematic;
un enum du genre:
```cpp
enum class eControlMode : uint8_t
{
    JOINT,
    CARTESIAN
}
```
serait plus clean

Aussi y'a pas vrm de lien entre forwardkinematic et joint mode ou inverseKinematic pour cartesian.

2024-07-07 19:40 UTC, Pmichaud29 commented on rover_arm/src/teleop.cpp
> +    void joyCallback(const rover_msgs::msg::Joy::SharedPtr joyMsg)
Peux tu laisser juste la déclaration ici et mettre la définition en bas du main comme avec le constructeur?

2024-07-07 19:40 UTC, Pmichaud29 commented on rover_msgs/msg/ArmCmd.msg
> +uint8 LINEAR = 0
JL (on s'est mit d'accord avec Alex haha)

2024-07-07 19:40 UTC, Pmichaud29 commented on rover_msgs/msg/ArmCmd.msg
> +
Rend ça cohérant avec les nouveaux nom que tu vas donner dans teleop.cpp

2024-07-07 19:40 UTC, Pmichaud29 commented on rover_sim/include/rover_lib/macros.h
Dupplicate

2024-07-07 19:40 UTC, Pmichaud29 commented on rover_sim/launch/rover_sim.launch.py
> +            namespace="/rover/arm",
Peut-être namespace /rover/arm/sim ?

2024-07-07 19:40 UTC, Pmichaud29 commented on rover_sim/launch/rover_sim.launch.py
> +                namespace="/rover/arm",
Peut-être namespace /rover/arm/sim ?

2024-07-07 19:40 UTC, Pmichaud29 commented on rover_sim/launch/rover_sim.launch.py
> +        executable='joint_state_publisher',
Met ça dans un namespace correspondant

2024-07-07 19:40 UTC, Pmichaud29 commented on rover_sim/launch/rover_sim.launch.py
> +        name='joint_state_publisher',
Donne lui un nom un peu plus parlant

2024-07-07 19:40 UTC, Pmichaud29 commented on rover_sim/launch/rover_sim.launch.py
> +        output="screen"
Met ça dans un namespace correspondant

2024-07-07 19:40 UTC, Pmichaud29 commented on rover_sim/src/encoder_status.cpp
> +    float _currentGripperOCPos = 0.0f;
Rename en fct de teleop

2024-07-07 19:40 UTC, Pmichaud29 commented on rover_sim/src/simulation_status.cpp
> +class Rover_sim_feedback : public rclcpp::Node
CamelCase

2024-07-12 14:35 UTC, Pmichaud29 requested changes
Pour le controle en joint tout à l'air perfect, est-ce que tu peux "enlever" le stock pour le cartesien? On va faire une pr différente pour ça. Ça va permettre de tester en joint dans un environnement stable (release)

2024-07-12 14:35 UTC, Pmichaud29 commented on rover_sim/launch/rover_sim.launch.py
> +        name='arm_sim_joint_state_publisher',
Vue qu'il est rendu dans nun namespace le "arm_sim" est un peu redondant

2024-07-12 21:38 UTC, closed without merging