Arm joint control + sim
robotique-udes/rover pull request #34
Opened 2024-07-12 21:39 UTC by emilesavoie

2024-07-17 17:20 UTC, Pmichaud29 requested changes

2024-07-17 17:20 UTC, Pmichaud29 commented on rover_arm/src/teleop.cpp
> +    float _posCmdJLLeft;
C'est un peu spécial de splitter ça, même si ça vient de deux boutons on va vouloir mapper ça sur une seule variable comme pour les autres joints

2024-07-17 17:20 UTC, Pmichaud29 commented on rover_arm/src/teleop.cpp
> +    float _gripperClose;
Même chose que lin, on va vouloir une variable

2024-07-17 17:20 UTC, Pmichaud29 commented on rover_sim/include/rover_lib/macros.h
Devrait pas être dans ce fichier là, normalement cette lib là est dans rover_msgs/include et en fonction de ton cmakefile tu vas pouvoir include

2024-07-17 17:20 UTC, Pmichaud29 commented on rover_sim/launch/rover_sim.launch.py
> +        output="screen"
il manque le namespace

2024-07-17 17:20 UTC, Pmichaud29 commented on rover_sim/src/simulation_status.cpp
Duplicate ou vieille version?

2024-07-17 22:54 UTC, emilesavoie commented on rover_sim/src/simulation_status.cpp
Pas sur de comprendre. C'est ni l'un ni l'autre

2024-07-18 04:36 UTC, emilesavoie commented on rover_sim/launch/rover_sim.launch.py
> +        output="screen"
Pour changer le namespace de robot_state_publisher, il faut remapper le namespace parce que c'est un noeud natif de ros (de ce que je comprend). Il faudrait donc faire le remapping sur chaque machine qui run le code. Si tu pense que ca vaut la peine, jvais le faire pi le rajouter dans le readme. Sinon tout est fini

2024-07-19 07:15 UTC, Pmichaud29 requested changes
Peux tu faire un court readme pour le bras (keybind, mode de control, etc) et ajoute l'info nécéssaire pour pouvoir utiliser le simulateur. Aussi rajoute les nouvelles dépendances dans le readme général pls (jpense pas que joint_state_... vient de base avec ros).

Aussi pour launch le sim ça serait bien que ça parte en fonction d'un argument de launch dans le rover.launch
ex: ros2 launch rover.launch.py simulate_arm:=true

2024-07-19 07:15 UTC, Pmichaud29 commented on rover_arm/src/teleop.cpp
> +    float _gripperMode;
bool

2024-07-19 07:15 UTC, Pmichaud29 commented on rover_arm/src/teleop.cpp
> +    float _speedControl = MAX_JOINT_SPEED; // 10 deg/s - (0.1745 rad/s)
Utilise directe le define dans le code à la place de lui attribuer de la mémoire

2024-07-19 07:15 UTC, Pmichaud29 commented on rover_sim/launch/rover_sim.launch.py
> +        output="screen"
Chiant, tu me montreras c'est quoi le fix et en fonction on choisiera. Pour l'instant laisse ça commenté pis crée un issue dans notre git

2024-07-19 07:15 UTC, Pmichaud29 commented on rover_sim/include/rover_lib/macros.h
À enlever

2024-07-22 02:59 UTC, Pmichaud29 approved these changes

2024-07-22 12:50 UTC, merged