New package rover_antenna
robotique-udes/rover pull request #51
Opened 2024-07-29 03:04 UTC by AudeR22

2024-07-29 15:37 UTC, Pmichaud29 requested changes
Quelques choses à revoir surtout dans le noeud qui envoie les commandes UDP. Sinon généralement bien.

Aussi, tout tes fichiers sont nommé antenna_* mais tes déjà dans le package rover_antenna donc c'est un peu redondant pour rien

2024-07-29 15:37 UTC, Pmichaud29 commented on rover_antenna/CMakeLists.txt
> +find_package(std_msgs REQUIRED)
old?

2024-07-29 15:37 UTC, Pmichaud29 commented on rover_antenna/package.xml
> +  <depend>std_msgs</depend>
old

2024-07-29 15:37 UTC, Pmichaud29 commented on rover_antenna/CMakeLists.txt
> +ament_target_dependencies(antennaJoy
snake_case

2024-07-29 15:37 UTC, Pmichaud29 commented on rover_antenna/src/antennaJoy.cpp
> +        if (_jogAverage_l1.getAverage() == 0.0f && _jogAverage_r1.getAverage() == 0.0f)
y'a quand même pomal d'enter haha

2024-07-29 15:37 UTC, Pmichaud29 commented on rover_antenna/src/antennaUDP.cpp
> +    ClientUDPAntenna(int sock, struct sockaddr_in servAddr, socklen_t sLen);
trailing underscore pour les arguments

2024-07-29 15:37 UTC, Pmichaud29 commented on rover_antenna/src/antennaUDP.cpp
> +    rclcpp::Publisher<rover_msgs::msg::AntennaCmd>::SharedPtr _pub_gps_antenna;
camelCase, pour les prefix ça va snake, ex: _pub_gpsAntenna

2024-07-29 15:37 UTC, Pmichaud29 commented on rover_antenna/src/antennaUDP.cpp
> +    rclcpp::TimerBase::SharedPtr _timer_send;
camelCase

2024-07-29 15:37 UTC, Pmichaud29 commented on rover_antenna/src/antennaUDP.cpp
> +        bool enable;
= 0.0

2024-07-29 15:37 UTC, Pmichaud29 commented on rover_antenna/src/antennaUDP.cpp
> +        float longitude;
= 0.0f

2024-07-29 15:37 UTC, Pmichaud29 commented on rover_antenna/src/antennaUDP.cpp
> +    char _bufferRecv[MAXLEN] = {'\0'};
maxlen vrm nécéssaire? Tu connais pas le size de tes packets?

2024-07-29 15:37 UTC, Pmichaud29 commented on rover_antenna/src/antennaUDP.cpp
> +            perror("socket creation failed");
roslog pls + continue

2024-07-29 15:37 UTC, Pmichaud29 commented on rover_antenna/src/antennaUDP.cpp
> +        RCLCPP_INFO(rclcpp::get_logger(""), "socketopt : %i", setsockopt(sock, SOL_SOCKET, SO_RCVTIMEO, (const char *)&tv, sizeof tv));
this->get_logger()
Pis pk un print pas un check sur le fail?

2024-07-29 15:37 UTC, Pmichaud29 commented on rover_antenna/src/antenna_abtr.cpp
> +        || (_arbitrationStatus.arbitration_status == rover_msgs::msg::AntennaArbitrationStatus::NOT_MOVING && _arbitrationRequest.target_arbitration == rover_msgs::srv::AntennaArbitration_Request::NO
Drole de bloc;
```cpp
if (_arbitrationStatus.arbitration_status == _arbitrationRequest.target_arbitration)
{
    _arbitrationResponse.success = true;
}
else
...
```
serait mieux

2024-07-29 15:37 UTC, Pmichaud29 commented on rover_antenna/src/antenna_abtr.cpp
> +        _arbitrationResponse.success = false;
on veut tu set le status à NOT_MOVING quand y'a un erreur?

2024-07-29 15:37 UTC, Pmichaud29 commented on rover_antenna/src/antenna_joy.cpp
> +    rclcpp::Parameter _paramCoeffNb;
Pas initialisé ni utilisé, jpense pas que tu peux faire des template static avec une variable nn plus

2024-07-29 15:37 UTC, Pmichaud29 commented on rover_antenna/src/antenna_joy.cpp
> +        RCLCPP_WARN(LOGGER, "No joy message is received");
Utilise un [RCLCPP_WARN_TROTTLE](https://answers.ros.org/question/352364/ros2-throttle-logs/) sinon tu vas floder le terminal

2024-07-29 15:37 UTC, Pmichaud29 commented on rover_antenna/src/antenna_udp.cpp
> +    ClientUDPAntenna(int sock, struct sockaddr_in servAddr, socklen_t sLen);
arg avec des trailing underscores

2024-07-29 15:37 UTC, Pmichaud29 commented on rover_antenna/src/antenna_udp.cpp
> +    rclcpp::Publisher<rover_msgs::msg::AntennaCmd>::SharedPtr _pub_gps_antenna;
camelCase

2024-07-29 15:37 UTC, Pmichaud29 commented on rover_antenna/src/antenna_udp.cpp
> +    rclcpp::TimerBase::SharedPtr _timer_send;
camelCase

2024-07-29 15:37 UTC, Pmichaud29 commented on rover_antenna/src/antenna_udp.cpp
> +        bool enable;
= 0.0

2024-07-29 15:37 UTC, Pmichaud29 commented on rover_antenna/src/antenna_udp.cpp
> +        float longitude;
= 0.0

2024-07-29 15:37 UTC, Pmichaud29 commented on rover_antenna/src/antenna_udp.cpp
> +    char _bufferRecv[MAXLEN] = {'\0'};
MAXLEN semble vrm overkill, tu devrais connaitre la taille exacte du packet nn?

2024-07-29 15:37 UTC, Pmichaud29 commented on rover_antenna/src/antenna_udp.cpp
> +            perror("socket creation failed");
RLCCPP_ERROR + continue

2024-07-29 15:37 UTC, Pmichaud29 commented on rover_antenna/src/antenna_udp.cpp
> +        RCLCPP_INFO(rclcpp::get_logger(""), "socketopt : %i", setsockopt(sock, SOL_SOCKET, SO_RCVTIMEO, (const char *)&tv, sizeof tv));
Peut-être rajoute un commentaire pour dire pk tu fais ça et pk un RCLCPP_INFO à place d'un if + continue comme en haut?

2024-07-29 15:37 UTC, Pmichaud29 commented on rover_antenna/src/antenna_udp.cpp
> +        servAddr.sin_addr.s_addr = inet_addr("192.168.140.100");
define

2024-07-29 15:37 UTC, Pmichaud29 commented on rover_antenna/src/antenna_udp.cpp
> +        }
pk un while pas un if + continue comme en plus haut?

2024-07-29 15:37 UTC, Pmichaud29 commented on rover_antenna/src/antenna_udp.cpp
> +        servAddr.sin_addr.s_addr = inet_addr("192.168.140.50");
define

2024-07-29 15:37 UTC, Pmichaud29 commented on rover_antenna/src/antenna_udp.cpp
> +    _sLen = sLen;
Attribue ça avant de partir tes sub/pub/timer dans le cas ou des callbacks serait call avant la fin de ton constructeur (jsais pas si c'est multithread mais dans l'éventualité où oui)

2024-07-29 15:37 UTC, Pmichaud29 commented on rover_antenna/src/antenna_udp.cpp
> +        RCLCPP_INFO(rclcpp::get_logger(""), "Bytes send : %f", _msgCbAbtr.speed);
Revoir les prints pour dequoi de plus pertinent en utilisation normal et non pour débug

2024-07-29 15:37 UTC, Pmichaud29 commented on rover_antenna/src/antenna_udp.cpp
> +        printf("recv failed\n");
print

2024-07-29 15:37 UTC, Pmichaud29 commented on rover_msgs/srv/AntennaArbitration.srv
> +uint8 success
tu l'utilises comme un bool dans le code

2024-08-01 02:06 UTC, AudeR22 commented on rover_antenna/CMakeLists.txt
> +find_package(std_msgs REQUIRED)
fait

2024-08-01 02:06 UTC, AudeR22 commented on rover_antenna/package.xml
> +  <depend>std_msgs</depend>
fait

2024-08-01 02:08 UTC, AudeR22 commented on rover_antenna/CMakeLists.txt
> +ament_target_dependencies(antennaJoy
fait

2024-08-01 02:08 UTC, AudeR22 commented on rover_antenna/src/antennaJoy.cpp
> +        if (_jogAverage_l1.getAverage() == 0.0f && _jogAverage_r1.getAverage() == 0.0f)
fait

2024-08-01 02:08 UTC, AudeR22 commented on rover_antenna/src/antennaUDP.cpp
> +    ClientUDPAntenna(int sock, struct sockaddr_in servAddr, socklen_t sLen);
fait

2024-08-01 02:08 UTC, AudeR22 commented on rover_antenna/src/antenna_udp.cpp
> +        servAddr.sin_addr.s_addr = inet_addr("192.168.140.50");
Comprend pas

2024-08-01 02:08 UTC, AudeR22 commented on rover_antenna/src/antenna_udp.cpp
> +    _sLen = sLen;
fait

2024-08-01 02:09 UTC, AudeR22 commented on rover_antenna/src/antenna_udp.cpp
> +        printf("recv failed\n");
fait

2024-08-01 02:09 UTC, AudeR22 commented on rover_msgs/srv/AntennaArbitration.srv
> +uint8 success
fait

2024-08-01 02:10 UTC, AudeR22 commented on rover_antenna/src/antenna_udp.cpp
> +        RCLCPP_INFO(rclcpp::get_logger(""), "Bytes send : %f", _msgCbAbtr.speed);
fait

2024-08-02 22:09 UTC, Pmichaud29 commented on rover_antenna/src/antenna_udp.cpp
> +        servAddr.sin_addr.s_addr = inet_addr("192.168.140.50");
Ton addresse devrait être un define en haut de ton code, d'un coup faut la changé

2024-08-02 22:51 UTC, AudeR22 commented on rover_antenna/src/antenna_abtr.cpp
> +        || (_arbitrationStatus.arbitration_status == rover_msgs::msg::AntennaArbitrationStatus::NOT_MOVING && _arbitrationRequest.target_arbitration == rover_msgs::srv::AntennaArbitration_Request::NO
fait

2024-08-02 22:54 UTC, AudeR22 commented on rover_antenna/src/antenna_abtr.cpp
> +        _arbitrationResponse.success = false;
Fait

2024-08-02 22:55 UTC, AudeR22 commented on rover_antenna/src/antenna_joy.cpp
> +    rclcpp::Parameter _paramCoeffNb;
fait

2024-08-02 23:21 UTC, AudeR22 commented on rover_antenna/src/antenna_joy.cpp
> +        RCLCPP_WARN(LOGGER, "No joy message is received");
fait

2024-08-02 23:22 UTC, AudeR22 commented on rover_antenna/src/antenna_udp.cpp
> +    rclcpp::Publisher<rover_msgs::msg::AntennaCmd>::SharedPtr _pub_gps_antenna;
Fait

2024-08-02 23:25 UTC, AudeR22 commented on rover_antenna/src/antenna_udp.cpp
> +    rclcpp::TimerBase::SharedPtr _timer_send;
Fait

2024-08-02 23:26 UTC, AudeR22 commented on rover_antenna/src/antenna_udp.cpp
> +        bool enable;
fait

2024-08-02 23:26 UTC, AudeR22 commented on rover_antenna/src/antenna_udp.cpp
> +        float longitude;
fait

2024-08-02 23:34 UTC, AudeR22 commented on rover_antenna/src/antenna_udp.cpp
> +    char _bufferRecv[MAXLEN] = {'\0'};
fait

2024-08-02 23:46 UTC, AudeR22 commented on rover_antenna/src/antenna_udp.cpp
> +            perror("socket creation failed");
fait

2024-08-02 23:57 UTC, AudeR22 commented on rover_antenna/src/antenna_udp.cpp
> +        servAddr.sin_addr.s_addr = inet_addr("192.168.140.100");
fait

2024-08-02 23:57 UTC, AudeR22 commented on rover_antenna/src/antenna_udp.cpp
> +        }
Fait

2024-08-02 23:58 UTC, AudeR22 commented on rover_antenna/src/antenna_udp.cpp
> +        servAddr.sin_addr.s_addr = inet_addr("192.168.140.50");
fait

2024-08-03 01:18 UTC, AudeR22 commented on rover_antenna/src/antenna_udp.cpp
> +        RCLCPP_INFO(rclcpp::get_logger(""), "socketopt : %i", setsockopt(sock, SOL_SOCKET, SO_RCVTIMEO, (const char *)&tv, sizeof tv));
fait

2024-08-03 20:28 UTC, Pmichaud29 requested changes

2024-08-03 20:28 UTC, Pmichaud29 commented on rover_antenna/launch/antenna.launch.py
> +                                  executable="joy_mode",
Mauvais nom, check le schema sur git

2024-08-03 20:28 UTC, Pmichaud29 commented on rover_antenna/launch/antenna.launch.py
> +                              executable="auto_mode",
Mauvais nom, check le schema sur git

2024-08-03 20:28 UTC, Pmichaud29 commented on rover_antenna/src/arbitration.cpp
> +        RCLCPP_ERROR(LOGGER, "Wrong service message!!! Message sent : %d. Expected 0, 1 or 2", _arbitrationRequest.target_arbitration);
Tu peux rajouter dans le print que tu arrête le moteur et avec ton implementation ça va spam ça à un rytme assez fulgurant donc tu pourrais faire un RCLCPP_ERROR_TROTTLED

2024-08-03 20:28 UTC, Pmichaud29 commented on rover_antenna/src/udp.cpp
> +#define MSGLEN 48
il vient d'où ton 48? c'est tu le size de ton union?

2024-08-03 20:28 UTC, Pmichaud29 commented on rover_antenna/src/udp.cpp
> +void signal_handler(int signo_);
camelCase (jsais que j'ai fait pareil, mais jpas bon)

2024-08-03 20:28 UTC, Pmichaud29 commented on rover_antenna/src/udp.cpp
> +        bool enable = 0.0;
0,0f

2024-08-03 20:28 UTC, Pmichaud29 commented on rover_antenna/src/udp.cpp
> +    struct MsgAbtrCmd
Pour les nom de struct on rajoute un s en prefix ex: sMsgAbtrCmd. Même chose pour les unions(u) et les enums(e). Aussi même si sont privé met les dans le top de ta classe vue que c'est des definitions

2024-08-03 20:28 UTC, Pmichaud29 commented on rover_antenna/src/udp.cpp
> +    char _bufferRecv[MSGLEN] = {'\0'};
uint8_t ça même affaire mais t'envoi pas des char interprettable par l'humain donc ça peut porter à confusion

2024-08-03 20:28 UTC, Pmichaud29 commented on rover_antenna/src/udp.cpp
> +            RCLCPP_ERROR(rclcpp::get_logger("udp_client(not init)"), "Sockect creation failed");
donne un peu plus d'info "Sockect creation failed, retrying at {rate}"

2024-08-03 20:28 UTC, Pmichaud29 commented on rover_antenna/src/udp.cpp
> +            RCLCPP_ERROR(rclcpp::get_logger("udp_client(not init)"), "Socket option failed");
samesies à plus haut

2024-08-03 20:28 UTC, Pmichaud29 commented on rover_antenna/src/udp.cpp
> +        close(sock);
Fait un close dans chacun de tes conditions de sorties ("continue;")

2024-08-03 21:52 UTC, AudeR22 commented on rover_antenna/launch/antenna.launch.py
> +                                  executable="joy_mode",
c'etait deja good

2024-08-03 21:52 UTC, AudeR22 commented on rover_antenna/launch/antenna.launch.py
> +                              executable="auto_mode",
c'etait deja good

2024-08-03 21:57 UTC, AudeR22 commented on rover_antenna/src/arbitration.cpp
> +        RCLCPP_ERROR(LOGGER, "Wrong service message!!! Message sent : %d. Expected 0, 1 or 2", _arbitrationRequest.target_arbitration);
fait

2024-08-03 21:59 UTC, AudeR22 commented on rover_antenna/src/udp.cpp
> +#define MSGLEN 48
fait

2024-08-03 22:00 UTC, AudeR22 commented on rover_antenna/src/udp.cpp
> +void signal_handler(int signo_);
fait

2024-08-03 22:02 UTC, AudeR22 commented on rover_antenna/src/udp.cpp
> +    struct MsgAbtrCmd
Dans le top c'est avant meme que je mettre mes public?

2024-08-03 22:02 UTC, AudeR22 commented on rover_antenna/src/udp.cpp
> +        bool enable = 0.0;
fait

2024-08-04 01:20 UTC, AudeR22 commented on rover_antenna/src/udp.cpp
> +    char _bufferRecv[MSGLEN] = {'\0'};
fait

2024-08-04 01:28 UTC, AudeR22 commented on rover_antenna/src/udp.cpp
> +        close(sock);
fait

2024-08-11 10:40 UTC, AudeR22 commented on rover_antenna/src/udp.cpp
> +            RCLCPP_ERROR(rclcpp::get_logger("udp_client(not init)"), "Sockect creation failed");
Live il retry a chaque loop, est-ce qu'il faudrait que j'y mette genre un chrono pour qui retry a un rate fixe et moins souvent?

2024-08-11 10:40 UTC, AudeR22 commented on rover_antenna/src/udp.cpp
> +            RCLCPP_ERROR(rclcpp::get_logger("udp_client(not init)"), "Socket option failed");
samesies à plus haut

2024-09-30 22:23 UTC, closed without merging